# This is a basic workflow to help you get started with Actions
name: Release
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types:
      - published
      - edited

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  new_release:
    name: "New Release"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1 --skip=1))
          echo $TAG
          echo "::set-output name=tag::$TAG"

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ steps.previoustag.outputs.tag }} # Change detection against merge-base with this branch
          list-files: "shell"
          filters: |
            main: src/main.py
            extract: src/extract/**

      - name: Echo results
        id: results
        run: |
          echo "${{ steps.changes.output.main_files }}"   
          echo "${{ steps.changes.output.extract_files }}"
